config/routes.rb
Final::Application.routes.draw do
  
  get "reviews/new"
  get "reviews/show"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :collections
  resources :books
  resources :reviews

  root 'users#index'

  

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :collection
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :books
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :collections
	has_many :books, :through => :collections
  authenticates_with_sorcery! 

  attr_accessor :password_confirmation
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def update
  end

  def new
    @book = current_user.books.new
  end

  def destroy
    @book = current_user.books.find(params[:id])
    @book.destroy
    redirect_to collection_path(@collection)
  end

  def create
    @book = Book.new(book_params)
    @book.collection_id = current_user.id
    if @book.save
      redirect_to collection_path(@collection)
    else
      render :new
    end
  end

  def edit
    @book = current_user.books.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :collection_id)
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @collections = Collection.all
    @collection = Collection.new

    # build and new
    # build = 
    # conllection.new
    # conleection.user_id = current_user.id
  end

  def show
    @collection = Collection.find(params[:id])
    @books = @collection.books
    @book = Book.new
    @show_path = true
    respond_to do |format|
      format.html
    end
  end

  def update
    @collection = Collection.find(params[:id])
    if @collection.update_attributes(collection_params)
      redirect_to @collection, notice: "Collection was updated Successfully"
    else
      render :edit
    end
  end

  def new
    @collection = current_user.collections.new
  end

  def destroy
    @collection = current_user.collections.find(params[:id])
    @collection.destroy

    redirect_to collections_url
  end

  def edit
    @collection = current_user.collections.find(params[:id])
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user_id = current_user.id
    if @collection.save
      redirect_to collections_path
    else
      render :new
    end
  end

  def search
    @collections = Collection.where("title LIKE '%#{params[:query]}%'")

    respond_to do |format|
      format.json { render @collections }
    end
  end

private

  def collection_params
    params.require(:collection).permit(:name, :user_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = login(params[:email], params[:password], params[:remember_me])
  	if user
  		redirect_back_or_to root_url, :notice => "Logged in!"
  	else
  		flash.now.alert = "email or password invalid"
  		render :new
  	end
  end

  def destroy
  	logout
  	redirect_to root_url, :notice => "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :find_user, :only => [:edit, :update, :destroy]

  def index
  	User.all
  end

  def new
  	@user = User.new
  end

	def create
  	@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id #logs the user in after registration
			redirect_to root_url, :notice => "Successfully signed up!"
		else
			render :new
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :remember_me)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<h1><%= @book.title %></h1>
<div class="container">
Author: <%= @book.author %>
</div>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<% provide(:title, 'Books') %>
<h1>Comics</h1>

app/views/books/new.html.erb
<h1>New Books</h1>

	<%= form_for @book do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :author %>
	<%= f.text_field :author %>
	<div>
		<%= f.submit "Add Comic" %>
	</div>
	<% end %>

app/views/books/show.html.erb
<%= render 'books/book' %>
<%= render 'reviews/show' %>
<%= render 'reviews/new' %>
<div class="container">
		<p><%= link_to "Back", collections_path(@collection) %></p>
</div>

app/views/collections/edit.html.erb
<h1>Edit Name</h1>

<%= form_for @collection do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<div>
		<%= f.submit %>
	</div>
	<% end %>
	<%= link_to "Back", collection_path %>

app/views/collections/index.html.erb
<% provide(:title, 'My Collections') %>
<h1>My Collections</h1>

<% if current_user %>
<div class="container">
<ul class="unstyled">
	<li><%= link_to "Owned", '#' %></li>
	<li><%= link_to "Wish List", '#' %></li>
	<li><%= link_to "Pull List", '#' %></li>
		<% @collections.each do |collection| %>
			<li><%= link_to collection.name, collection_path(collection)%> (<%= collection.books.count %>)</li>
		<% end %>
		<%= form_for @collection do |f| %>
			<%= f.text_field :name %><br />
			<%= f.submit %>
		<% end %>
	<% else %>
		<p><%= link_to "Login", login_path %> or <%= link_to "Sign up", signup_path %> to add Collections</p>
<% end %>
</ul>
<%= link_to 'Back', root_path %>
</div>

app/views/collections/new.html.erb
<% provide(:title, 'New Collection') %>
<h1>New Collection</h1>
<%= form_for @collection do |f| %>
	<%= f.text_field :name %><br />
	<%= f.submit %>
<% end %>

app/views/collections/show.html.erb
<% provide(:title, 'Collections') %>
<h1><%= @collection.name %></h1>
<div class="container">
This collection contains <%= @collection.books.count %> comics<br/>
<%= link_to 'Edit', edit_collection_path(@collection) %>
<div>
	<%= link_to 'Add Comic', new_book_path, class: 'btn btn-inverse' %>
</div>

<% if current_user == @collection.user %>
	<% @books.each do |book| %>
	<div class="well">
		Title: <%=link_to book.title, book %><br/>
		Issue:<br/>
		Author: <%= book.author %><br/>
		<%= link_to "Delete Comic", book, class: 'btn btn-danger', method: :delete, data: { confirm: "Delete this book?" } %>
	</div>
<% end %>
	
	<div>
		<%= link_to 'Delete Collection', @collection, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<p><%= link_to 'Back', collections_path %></p>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Comic DataBox", root_url %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "FAQ", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">	
				<%= link_to "Comic Databox", root_url, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<form class="navbar-search pull-left">
          		<input type="text" class="search-query" id="search" autocomplete="off" placeholder="Search"></input>
        		</form>

						<li class="<%= 'active' if current_page? collections_path or @show_path %>"><%= link_to "My Collections", collections_path %></li>
						
						<% if current_user %>
							<li class="<%= 'active' if current_page? user_path(:id) %>"><%= link_to current_user.email, user_path(:id) %></li>
							<li><%= link_to "Logout", logout_path %></li>
						<% else %>
						
							<li><%= link_to "Sign in", login_path %></li>
						<% end %>

					</ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comic Databox | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/reviews/_new.html.erb
<h1>New Review</h1>

app/views/reviews/_show.html.erb
<h1>Reviews for <%= @book.title %><h1>

app/views/users/index.html.erb
<% provide(:title, 'Home') %>
<% if current_user %>
	<div class="container">
		<div class="span12">
			<%= image_tag("image1.jpg", :size => "200x180", :crop => :fill) %>
			<%= image_tag("image2.jpg", :size => "200x180", :crop => :fill) %>
			<%= image_tag("image3.jpg", :size => "200x180", :crop => :fill) %>
			<%= image_tag("image4.jpg", :size => "200x180", :crop => :fill) %>
		</div>
	</div>

<% else %>

	<div class="center hero-unit">
		<h1 id="comicred">Comic<span id="datab">Data</span><span id="dbox">Box</span></h1>
		<h2>Your online resource for your growing comicbook collection</h2>
		<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<div>
<%= f.submit %>
</div>
<% end %>

app/views/users/show.html.erb
<h1>User Information</h1>